import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <div className='w-full max-w-[1200px] mx-auto grid grid-cols-1 md:grid-cols-6 lg:grid-cols-6'>
          <div className='bg-pink-200 hidden lg:grid lg:col-span-1'>one</div>
          <div className='bg-sky-200 md:col-span-5 lg:col-span-4'>
            {children}
          </div>
          <div className='bg-zinc-200 row-start-1 md:grid md:col-span-1 md:col-start-6'>
            three
          </div>
        </div>
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/github-dark.min.css'
        />
      </body>
    </html>
  );
}
